version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=superheroes
    ports:
      - "5432:5432"
    volumes:
      -  ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      -  superheroes-db:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4:6.18
#    environment:
#      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
#      PGADMIN_DEFAULT_PASSWORD: 'admin'
#    ports:
#      - 80:80

volumes:
  superheroes-db: